rm(list=ls());gc()
library(lubridate)
library(tidyverse)
library(StatMeasures)
library(tibbletime)
library(foreach)
library(ggplot2)
library(data.table)
setwd("C:/Users/USER/Desktop/finance management/財策")
###################
suspend.Add<-fread("addition.txt",data.table = F)
contdb<-fread("contdb.txt",data.table = F)
colnames(suspend.Add)<-c("code","name","ym","quarter","month","Dbratio","ttasset","ltdebt","eps","ebitps")
suspend.Add$ym<-as.Date(paste0(suspend.Add$ym,"01"),"%Y%m%d")
colnames(contdb)<-c("code","name","ym","contdb_equ")
contdb$ym<-as.Date(paste0(contdb$ym,"01"),"%Y%m%d")
contdb$contdb_equ<-as.numeric(contdb$contdb_equ)
ggplot(data=suspend.Add,aes(x=ym,y=Dbratio,col=name))+geom_line(size=1)+ggtitle("大同和問題子公司負債比走勢")+labs(x="時間",y="負債比")+ggsave("debtadd.jpg")
ggplot(data=suspend.Add,aes(x=ym,y=ltdebt/ttasset,col=name))+geom_line(size=1)+ggtitle("大同和問題子公司長期負債比走勢")+labs(x="時間",y="長期負債比")+ggsave("ltdebtadd.jpg")
ggplot(data=suspend.Add,aes(x=ym,y=eps,col=name))+geom_line(size=1)+ggtitle("大同和問題子公司每股盈餘走勢")+labs(x="時間",y="每股盈餘")+ggsave("eps.jpg")
ggplot(data=suspend.Add,aes(x=ym,y=ebitps,col=name))+geom_line(size=1)+ggtitle("大同和問題子公司每股EBIT走勢")+labs(x="時間",y="ebitps")+ggsave("ebitps.jpg")
ggplot(data=contdb %>% na.omit(),aes(x=ym,y=contdb_equ,col=name))+geom_line(size=1)+ggtitle("大同和問題子公司或有負債/淨值走勢")+labs(x="時間",y="或有負債/淨值")+ggsave("cont.jpg")
